"""stage7 job leases and city checkpoints

Revision ID: 165a424d6ba1
Revises: 9cbc48c31e6e
Create Date: 2026-10-01 20:22:06.574354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165a424d6ba1'
down_revision: Union[str, Sequence[str], None] = '9cbc48c31e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
