"""stage2 material version parameter sources

Revision ID: 5c968a541440
Revises: df85b07c9163
Create Date: 2026-09-28 22:27:44.173024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c968a541440'
down_revision: Union[str, Sequence[str], None] = 'df85b07c9163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_versions', sa.Column('parameter_sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_versions', 'parameter_sources_json')
    # ### end Alembic commands ###
