"""create simulation jobs

Revision ID: 933e5fc5bb27
Revises: 
Create Date: 2026-08-04 09:57:59.602243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '933e5fc5bb27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(length=100), nullable=False),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_celery_task_id'), 'simulation_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_city_id'), 'simulation_jobs', ['city_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_status'), 'simulation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_jobs_status'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_city_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_celery_task_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    # ### end Alembic commands ###
