"""stage7 job leases and city checkpoints

Revision ID: 9cbc48c31e6e
Revises: a1f4c2d9e7b3
Create Date: 2026-10-01 19:49:43.182771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cbc48c31e6e'
down_revision: Union[str, Sequence[str], None] = 'a1f4c2d9e7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_city_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city_result_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_result_id'], ['global_city_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_result_id', 'month', name='uq_global_city_checkpoint_month')
    )
    op.create_index(op.f('ix_global_city_checkpoints_city_result_id'), 'global_city_checkpoints', ['city_result_id'], unique=False)
    op.add_column('global_batch_jobs', sa.Column('attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('global_batch_jobs', sa.Column('lease_owner', sa.String(length=100), nullable=True))
    op.add_column('global_batch_jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('global_batch_jobs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('global_batch_jobs', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_global_batch_jobs_lease_expires_at'), 'global_batch_jobs', ['lease_expires_at'], unique=False)
    op.add_column('global_city_results', sa.Column('lease_owner', sa.String(length=100), nullable=True))
    op.add_column('global_city_results', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_global_city_results_lease_reap', 'global_city_results', ['status', 'lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_global_city_results_lease_reap', table_name='global_city_results')
    op.drop_column('global_city_results', 'lease_expires_at')
    op.drop_column('global_city_results', 'lease_owner')
    op.drop_index(op.f('ix_global_batch_jobs_lease_expires_at'), table_name='global_batch_jobs')
    op.drop_column('global_batch_jobs', 'cancel_requested_at')
    op.drop_column('global_batch_jobs', 'last_heartbeat_at')
    op.drop_column('global_batch_jobs', 'lease_expires_at')
    op.drop_column('global_batch_jobs', 'lease_owner')
    op.drop_column('global_batch_jobs', 'attempt')
    op.drop_index(op.f('ix_global_city_checkpoints_city_result_id'), table_name='global_city_checkpoints')
    op.drop_table('global_city_checkpoints')
    # ### end Alembic commands ###
