"""add global batch analysis tables

Revision ID: 9e0b460c56c3
Revises: b83aed15c819
Create Date: 2026-09-05 17:33:28.446645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e0b460c56c3'
down_revision: Union[str, Sequence[str], None] = 'b83aed15c819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_batch_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('celery_group_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_city_count', sa.Integer(), nullable=False),
    sa.Column('completed_city_count', sa.Integer(), nullable=False),
    sa.Column('failed_city_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_city_count', sa.Integer(), nullable=False),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_batch_jobs_celery_group_id'), 'global_batch_jobs', ['celery_group_id'], unique=False)
    op.create_index(op.f('ix_global_batch_jobs_status'), 'global_batch_jobs', ['status'], unique=False)
    op.create_table('global_city_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.String(length=100), nullable=False),
    sa.Column('city_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('climate_adaptation_rate_percent', sa.Float(), nullable=True),
    sa.Column('annual_average_skin_improvement_c', sa.Float(), nullable=True),
    sa.Column('annual_average_core_improvement_c', sa.Float(), nullable=True),
    sa.Column('maximum_skin_improvement_c', sa.Float(), nullable=True),
    sa.Column('effective_cooling_hours', sa.Float(), nullable=True),
    sa.Column('evaluated_weighted_days', sa.Integer(), nullable=True),
    sa.Column('beneficial_weighted_days', sa.Integer(), nullable=True),
    sa.Column('monthly_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['global_batch_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'city_id', name='uq_global_batch_city')
    )
    op.create_index(op.f('ix_global_city_results_batch_id'), 'global_city_results', ['batch_id'], unique=False)
    op.create_index(op.f('ix_global_city_results_celery_task_id'), 'global_city_results', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_global_city_results_city_id'), 'global_city_results', ['city_id'], unique=False)
    op.create_index(op.f('ix_global_city_results_status'), 'global_city_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_city_results_status'), table_name='global_city_results')
    op.drop_index(op.f('ix_global_city_results_city_id'), table_name='global_city_results')
    op.drop_index(op.f('ix_global_city_results_celery_task_id'), table_name='global_city_results')
    op.drop_index(op.f('ix_global_city_results_batch_id'), table_name='global_city_results')
    op.drop_table('global_city_results')
    op.drop_index(op.f('ix_global_batch_jobs_status'), table_name='global_batch_jobs')
    op.drop_index(op.f('ix_global_batch_jobs_celery_group_id'), table_name='global_batch_jobs')
    op.drop_table('global_batch_jobs')
    # ### end Alembic commands ###
