"""add material version and spectrum tables

Revision ID: b83aed15c819
Revises: 933e5fc5bb27
Create Date: 2026-08-12 09:46:37.814874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b83aed15c819'
down_revision: Union[str, Sequence[str], None] = '933e5fc5bb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_is_archived'), 'materials', ['is_archived'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_index(op.f('ix_materials_slug'), 'materials', ['slug'], unique=True)
    op.create_table('material_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('clothing_insulation_clo', sa.Float(), nullable=False),
    sa.Column('evaporative_resistance_m2pa_w', sa.Float(), nullable=True),
    sa.Column('solar_reflectance', sa.Float(), nullable=False),
    sa.Column('solar_transmittance', sa.Float(), nullable=False),
    sa.Column('infrared_emissivity', sa.Float(), nullable=False),
    sa.Column('infrared_transmittance', sa.Float(), nullable=False),
    sa.Column('projected_solar_area_factor', sa.Float(), nullable=False),
    sa.Column('absorbed_solar_to_body_fraction', sa.Float(), nullable=False),
    sa.Column('areal_density_g_m2', sa.Float(), nullable=True),
    sa.Column('specific_heat_j_kgk', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('infrared_emissivity >= 0 AND infrared_emissivity <= 1', name='ck_material_ir_emissivity'),
    sa.CheckConstraint('infrared_transmittance >= 0 AND infrared_transmittance <= 1', name='ck_material_ir_transmittance'),
    sa.CheckConstraint('solar_reflectance + solar_transmittance <= 1.000001', name='ck_material_solar_energy_sum'),
    sa.CheckConstraint('solar_reflectance >= 0 AND solar_reflectance <= 1', name='ck_material_solar_reflectance'),
    sa.CheckConstraint('solar_transmittance >= 0 AND solar_transmittance <= 1', name='ck_material_solar_transmittance'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'version_number', name='uq_material_version_number')
    )
    op.create_index(op.f('ix_material_versions_material_id'), 'material_versions', ['material_id'], unique=False)
    op.create_table('material_spectra',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_version_id', sa.String(length=36), nullable=False),
    sa.Column('spectrum_type', sa.String(length=50), nullable=False),
    sa.Column('wavelength_unit', sa.String(length=20), nullable=False),
    sa.Column('points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('minimum_wavelength_um', sa.Float(), nullable=False),
    sa.Column('maximum_wavelength_um', sa.Float(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_version_id'], ['material_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_version_id', 'spectrum_type', name='uq_material_version_spectrum_type')
    )
    op.create_index(op.f('ix_material_spectra_material_version_id'), 'material_spectra', ['material_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_spectra_material_version_id'), table_name='material_spectra')
    op.drop_table('material_spectra')
    op.drop_index(op.f('ix_material_versions_material_id'), table_name='material_versions')
    op.drop_table('material_versions')
    op.drop_index(op.f('ix_materials_slug'), table_name='materials')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_is_archived'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
