"""add stage 4 4 checkpoint and analytics fields

Revision ID: df85b07c9163
Revises: e4ee64441802
Create Date: 2026-09-08 20:45:43.789201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df85b07c9163'
down_revision: Union[str, Sequence[str], None] = 'e4ee64441802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_city_results', sa.Column('completed_month_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('global_city_results', sa.Column('last_checkpoint_month', sa.Integer(), nullable=True))
    op.add_column('global_city_results', sa.Column('resumed_from_checkpoint', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('global_city_results', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('global_city_results', sa.Column('skin_improvement_p50_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('skin_improvement_p90_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('skin_improvement_p95_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('core_improvement_p50_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('core_improvement_p90_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('core_improvement_p95_c', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('heatwave_event_count', sa.Integer(), nullable=True))
    op.add_column('global_city_results', sa.Column('longest_heatwave_days', sa.Integer(), nullable=True))
    op.add_column('global_city_results', sa.Column('analytics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_city_results', 'analytics_json')
    op.drop_column('global_city_results', 'longest_heatwave_days')
    op.drop_column('global_city_results', 'heatwave_event_count')
    op.drop_column('global_city_results', 'core_improvement_p95_c')
    op.drop_column('global_city_results', 'core_improvement_p90_c')
    op.drop_column('global_city_results', 'core_improvement_p50_c')
    op.drop_column('global_city_results', 'skin_improvement_p95_c')
    op.drop_column('global_city_results', 'skin_improvement_p90_c')
    op.drop_column('global_city_results', 'skin_improvement_p50_c')
    op.drop_column('global_city_results', 'last_heartbeat_at')
    op.drop_column('global_city_results', 'resumed_from_checkpoint')
    op.drop_column('global_city_results', 'last_checkpoint_month')
    op.drop_column('global_city_results', 'completed_month_count')
    # ### end Alembic commands ###
