"""add stage 4 2 exposure and retry fields

Revision ID: e4ee64441802
Revises: 9e0b460c56c3
Create Date: 2026-09-06 03:53:31.078902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ee64441802'
down_revision: Union[str, Sequence[str], None] = '9e0b460c56c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_city_results', sa.Column('exposure_coverage_percent', sa.Float(), nullable=True))
    op.add_column('global_city_results', sa.Column('sampled_day_count', sa.Integer(), nullable=True))
    op.add_column('global_city_results', sa.Column('eligible_sample_count', sa.Integer(), nullable=True))
    op.add_column('global_city_results', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_city_results', 'retry_count')
    op.drop_column('global_city_results', 'eligible_sample_count')
    op.drop_column('global_city_results', 'sampled_day_count')
    op.drop_column('global_city_results', 'exposure_coverage_percent')
    # ### end Alembic commands ###
