"""Render docs/model-parameters.md from the registry."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services.model_parameters import (  # noqa: E402
    MODEL_PARAMETER_SET_VERSION,
    list_model_parameters,
    model_parameter_set_sha256,
)

lines = [
    "# Model parameters",
    "",
    f"Parameter set version: `{MODEL_PARAMETER_SET_VERSION}`  ",
    f"SHA-256: `{model_parameter_set_sha256()}`",
    "",
    "Generated by `scripts/render_model_parameters_doc.py`. Do not edit by hand.",
    "",
    "| name | value | unit | source type | reference | note |",
    "|---|---|---|---|---|---|",
]

for p in list_model_parameters():
    lines.append(
        f"| `{p.name}` | {p.value:g} | {p.unit} | {p.source_type} | {p.reference} | {p.note or ''} |"
    )

Path(sys.argv[1]).write_text("\n".join(lines) + "\n", encoding="utf-8")